routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//
// Route::get('/', function () {
//     return view('blog/home');
// });
// Route::get('/w', function () {
//     return view('welcome');
// });

Route::get('/' , 'PostController@publicHomePage')->name('getPublic');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('posts','PostController');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class blog extends Model
{
    //
}

app/post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class post extends Model
{
    //
}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BlogController extends Controller
{
    //
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\post;
use Illuminate\Http\Request;
use Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $logedid = Auth::id();
      $posts = post::all()->where('user_id',$logedid);
      return view('adminPanel/home', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('adminPanel.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $post = new post;

        $post->user_id = Auth::id();
        $post->title = $request->title;
        $post->body = $request->body;
        $post->save();

        return redirect()->route('posts.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(post $post)
    {

      $thePost = post::find($post->id);
        return view('blog.viewPost',compact('thePost'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(post $post)
    {
      return view('adminPanel.edit',compact('post'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, post $post)
    {
        $thePost = Post::find($post->id);
        $page ="";

        if (isset($request->commentCount))
        {
          $commentCount = $request->commentCount;
          $thePost->comment_count = $commentCount;
          $page = "posts.show";
        }

        if (isset($request->visitCount))
        {
          $visitCount = $request->visitCount;
          $thePost->visit_count = $visitCount;
          $page = "posts.show";
        }

        if (isset($request->title))
        {
          $thePost->title = $request->title;
          $page = "posts.index";
        }

        if (isset($request->body))
        {
          $thePost->body = $request->body ;
        }

        $thePost->save();



        return redirect()->route($page,compact('thePost'));
      }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(post $post)
    {
        $post->delete();

        return redirect()->back();
    }

    public function publicHomePage(Request $request)
    {
      if($request->input('type') == 'recentPosts')
      {
        $post = Post::orderBy('created_at','asc')->paginate(10);
        $orginazation = 'Top 10 most Recent Posts';
      }
      else if ($request->input('type') == 'commentPosts')
      {
        $post = Post::orderBy('comment_count','desc')->paginate(10);
        $orginazation = 'Top 10 Most Commented posts';
      }
      else if($request->input('type') == 'visitPosts')
      {
        $post = Post::orderBy('visit_count','desc')->paginate(10);
        $orginazation = 'Top 10 Most visited posts';
      }
      else
      {
        $post = Post::orderBy('created_at','asc')->paginate(10);
        $orginazation = 'Top 10 most Recent Posts';
      }

      $data = array(
        'post' => $post,
        'orginazation' => $orginazation
      );

        return view('blog/home', $data);
    }
}

resources/views/adminPanel/create.blade.php
@extends('layouts.templete')

@section('title' , 'Add New Post')

@section('content')
  <h1>Add New Post</h1>
  <div class="col-sm-8 col-sm-offset-2">

    <form class="" action="{{route('posts.store')}}" method="post">
      {{csrf_field()}}
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" name="title" value="" class="form-control">
      </div>

      <div class="form-group">
        <label for="body">Body:</label>
        <textarea name="body" rows="8" cols="80" class="form-control"></textarea>
      </div>

      <button type="submit" name="button" class="btn btn-primary">Submit</button>
      <a href="{{route('posts.index')}}" class="btn btn-primary">Go Back</a>
    </form>

  </div>
@endsection

resources/views/adminPanel/edit.blade.php
@extends('layouts.templete')

@section('title' , 'Edit Post #'. $post->id)

@section('content')
  <h1>Edit Post #{{$post->id}}</h1>
  <div class="col-sm-8 col-sm-offset-2">

    <form class="" action="{{route('posts.update',['id'=>$post->id])}}" method="post">
      {{csrf_field()}}
      <input type="hidden" name="_method" value="PUT">
      <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" name="title" value="{{$post->title}}" class="form-control">
      </div>

      <div class="form-group">
        <label for="body">Body:</label>
        <textarea name="body" rows="8" cols="80" class="form-control" >{{$post->body}}</textarea>
      </div>

      <button type="submit" name="button" class="btn btn-primary">Submit</button>
      <a href="{{route('posts.index')}}" class="btn btn-primary">Go Back</a>
    </form>

  </div>
@endsection

resources/views/adminPanel/home.blade.php
@extends('layouts.templete')

@section('title' , 'Blog Admin Panel')
@section('content')
<a href="/">Go Back To Home</a>

<div class="nav navbar-nav pull-right">
  <li class="nav-item dropdown">
      <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
          {{ Auth::user()->name }} <span class="caret"></span>
      </a>

      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="{{ route('logout') }}"
             onclick="event.preventDefault();
                           document.getElementById('logout-form').submit();">
              {{ __('Logout') }}
          </a>

          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
          </form>
      </div>
  </li>
</div> <h1>admin panel</h1>

<a href="{{route('posts.create')}}" class="btn btn-primary pull-right">Add New Blog Post</a>

<br><br><br>

<table class="table">
  <thead>
    <th>id</th>
    <th>title</th>
    <th>body</th>
    <th>edit</th>
    <th>delete</th>
  </thead>
  @foreach ($posts as $post)

  <tbody>
    <td>{{$post->id}}</td>
    <td>{{$post->title}}</td>
    <td>{{$post->body}}</td>
    <td><a href="{{route('posts.edit',['id' => $post->id])}}" class="btn btn-info">Edit</a> </td>
    <td><form action="{{route('posts.destroy',['id' => $post->id])}}" method="post">
      {{csrf_field()}}
      <input type="hidden" name="_method" value="DELETE">
         <input type="submit" class="btn btn-danger" value="Delete">
    </form>
  </tbody>
  @endforeach

</table>
@endsection

resources/views/blog/home.blade.php
@extends('layouts.PublicHomePageTemplete')

@section('title' ,'Blog home page')

@section('content')
<div>
<h2>{{$orginazation}}</h2>
@foreach($post as $p)

<div class="well well-lg">

<h3>{{$p->title}}</h3>

<p>{{$p->body}}</p>

<br>
<br>
<p>Comment Count: {{$p->comment_count}}</p>
<p>Post created At: {{date('F d, Y', strtotime($p->created_at))}} at {{date('g:ia', strtotime($p->created_at))}}</p>
<p>visit Count: {{$p->visit_count}}</p>
<a href="{{route('posts.show',['id'=>$p->id])}}" class="btn btn-default pull-right">View Post</a>

&nbsp;
</div>



@endforeach
<div class="row text-center">
{{$post->links()}}
</div>
</div>
@endsection('content')

resources/views/blog/viewPost.blade.php
@extends('layouts.viewPostTemplete')
@section('title','View Post #'. $thePost->id)

@section('content')
<div id="fbCommentCount" style="Display:none;">
  <span class="fb-comments-count" data-href="http://newblog.test/posts/{{$thePost->id}}"></span>
</div>
<form style="Display:none;" action="{{route('posts.update',['id' => $thePost->id])}}" method="post">
  {{csrf_field()}}
  <input type="hidden" name="_method" value="PUT">

  <input type="text" name="commentCount" id="fbCommentCounts">

  <input type="text"  value="{{$thePost->visit_count}}" id="postVisitCount" name="visitCount">
</form>


<div class="row">
<h1>{{$thePost->title}}</h1>
<p>{{$thePost->body}}</p>
</div>

<div class="row text-center" id="facebookCommentContainer">
<div class="fb-comments" data-href="http://newblog.test/posts/{{$thePost->id}}" data-width="800" data-numposts="5"></div>
</div>

<script>
 let fbCommentCount = document.getElementById('fbCommentCount').getElementsByClassName('fb_comments_count');

setTimeout(function(){
  document.getElementById('fbCommentCounts').value = fbCommentCount[0].innerHTML;

let visitCount = document.getElementById('postVisitCount').value;
let visitCountPlusOne = parseInt(visitCount) + 1;
document.getElementById('postVisitCount').value = visitCountPlusOne;
  let $formVar = $('form');
  $.ajax({
    url: $formVar.prop('{{ route('posts.update' , ['id'=> $thePost->id])}}'),
    method: 'PUT',
    data:$formVar.serialize()
  });
}, 1000);


</script>
@endsection('content')

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/PublicHomePageTemplete.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>@yield('title')</title>
  </head>
  <body>
    <div class="container">
      <a href="/">Go Back To Home</a>

        <div class="loginBox nav navbar-nav pull-right">
          @guest
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
              </li>
          @else
              <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ route('logout') }}"
                         onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
          @endguest
        </div>

        <div>
          <h1>welcom to the blog</h1>
        </div>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="" class="dropdown-toggle" data-toggle="dropdown">sort posts by <span class="caret"></span> </a>
        <ul class="dropdown-menu" >
          <li><a href="{{route('getPublic',['type' => 'recentPosts'])}}">Top 10 most Recent Posts</a></li>
          <li><a href="{{route('getPublic',['type' => 'commentPosts'])}}">Top 10 Most Commented posts</a></li>
          <li><a href="{{route('getPublic',['type' => 'visitPosts'])}}">Top 10 Most visited posts</a></li>
        </ul>

      </li>

  </ul>
@if(Auth::check())
<ul class="nav navbar-nav navbar-right">
  <li><a href="{{route('posts.index')}}">Manage Blog Posts</a> </li>
</ul>
@endif
  </div>
</nav>

<div>
  @yield('content')

  <div class="footer text-center" style="margin: 20px 0 60px 0;">
    <p>&copy; Begin programming</p>
  </div>
    </div>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/templete.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
      integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
      crossorigin="anonymous">

    <title>@yield('title')</title>
  </head>
  <body>
    <div class="container">
      @yield('content')
    </div>

    <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous">
   </script>

   <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous">
   </script>
  </body>
</html>

resources/views/layouts/viewPostTemplete.blade.php
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <title>@yield('title')</title>
  </head>
  <body>
<!-- facbook comment system sdk script -->
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ar_AR/sdk.js#xfbml=1&version=v3.1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

    <div class="container">
<a href="/">Go Back To Home</a>
        <div class="loginBox nav navbar-nav pull-right">
          @guest
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
              </li>
          @else
              <li class="nav-item dropdown">
                  <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                      {{ Auth::user()->name }} <span class="caret"></span>
                  </a>

                  <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                      <a class="dropdown-item" href="{{ route('logout') }}"
                         onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">
                          {{ __('Logout') }}
                      </a>

                      <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                          @csrf
                      </form>
                  </div>
              </li>
          @endguest
        </div>


<div>
  @yield('content')

  <div class="footer text-center" style="margin: 20px 0 60px 0;">
    <p>&copy; Begin programming</p>
  </div>
    </div>
    <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </body>
</html>